# action.yml
name: Python test
on:
  push:
    branches: [ xyz ]
jobs:
  gpu_checks:
    name: Tests (Cuda, Python) =
    runs-on: self-hosted
    strategy:
      matrix:
        cuda-version: ['10.1', '10.2']
        python-version: ['3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
      with:
        cuda-version: ${{ matrix.cuda-version }}
        python-version: ${{ matrix.python-version }}
    - name: Run GPU tests CUDA=${{ matrix.cuda-version }} & Python${{ matrix.python-version }}
      run: |
        cd .github/workflows/graveyard
        make docker-test-run-zsh CUDA=${{ matrix.cuda-version }} Python=${{ matrix.python-version }}
